#!/bin/bash
WHEREAMI=$0

# Follow until we get our symlink resolved, since
# homebrew has multiple hops.
cd $(dirname $WHEREAMI)
while [ -h "$WHEREAMI" ]; do
  DEST=$(readlink $WHEREAMI)
  cd $(dirname $DEST)
  WHEREAMI=$(dirname $WHEREAMI)"/"$DEST
done

python ./src/example.py
